mysql:
  host: "127.0.0.1"
  port: 3306
  user: "tester"
  password: "testing"
  dbname: "foundationService"

wifiDB:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "radius"

metablox:
  wallet:
    keystore: "../.wallet/keystore/UTC--1970-01-01T01-01-01.621982800Z--1234567890123456789012345678901234567890"
    passphrase: "123456"

  rpcUrl: "https://api.s0.b.hmny.io"
  registryContract: "your registry contract address"

logger:
  path: "../logs/"
  file: "foundation.log"
  level: "debug"
  stdout: true
  rotateTime: 24
  rotateLimit: 7
