storage:
  key_saving: "./wallet/"
  key_loading: "./wallet/"
  issuer_key_file: "issuer"
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "tester"
  password: "testing"
  dbname: "foundationService"
  testhost: "127.0.0.1"
  testport: 3306
  testuser: "tester"
  testpassword: "testing"
  testdbname: "foundationservicetest"