storage:
  key_saving: "../.wallet/"
  key_loading: "../.wallet/"
  issuer_key_file: "issuer"
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "tester"
  password: "testing"
  dbname: "foundationService"

wifiDB:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "radius"

metablox:
  rpcUrl: "https://api.s0.b.hmny.io"
  registryContract: "your registry contract address"

logger:
  path: "../logs/"
  file: "foundation.log"
  level: "debug"
  stdout: true
  rotateTime: 24
  rotateLimit: 7
