
storage:
  key_saving: "./wallet/"
  key_loading: "./wallet/"
  issuer_key_file: "issuer"

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "tester"
  password: "testing"
  dbname: "foundationService"

wifiDB:
  host: "172.31.8.73"
  port: 3309
  user: "root"
  password: "123456"
  dbname: "radius"

metablox:
  rpcUrl: "https://api.s0.b.hmny.io"
  registryContract: "0x3F4b2552e04c0EeDd1054272F46Bf90cAA143d51"
