storage:
  key_saving: "./wallet/"
  key_loading: "./wallet/"
  issuer_key_file: "issuer"
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "tester"
  password: "testing"
  dbname: "foundationService"
  testhost: "127.0.0.1"
  testport: 3306
  testuser: "tester"
  testpassword: "testing"
  testdbname: "foundationservicetest"

metablox:
  rpcUrl: "https://api.s0.b.hmny.io"
  wssUrl: "wss://ws.s0.b.hmny.io"
  registryContract: "0xf880b97Be7c402Cc441895bF397c3f865BfE1Cb2"