storage:
  key_saving: "./wallet/"
  key_loading: "./wallet/"
  issuer_key_file: "issuer"
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "tester"
  password: "testing"
  dbname: "foundationService"

metablox:
  rpcUrl: "https://api.s0.ps.hmny.io/"
  registryContract: "0x8a9DE3908DDD37b1F2D46D875214237C0505BF94"